In [2]:
#print the first 10 fib numbers
def fib(n):
    a,b = 0,1
    for i in range(n):
        print(a)
        a,b = b,a+b

fib(10)

0
1
1
2
3
5
8
13
21
34


In [3]:
fib (5)

0
1
1
2
3


In [5]:
a = ("b")

In [6]:
bool(a == 2)

False

In [7]:
a == 2

False

In [8]:
bool (10)

True

In [9]:
bool(0)

False

In [12]:
b = 1
d = 0

if bool (b + d) == False:
    print("False")
    
elif bool (b + d) == True:
    print("True")



True


In [13]:
#ask the user to enter a nmber for the values of b and d
b = int(input("Enter the value of b: "))
d = int(input("Enter the value of d: "))
if bool (b + d) == False:
    print("False")

elif bool (b + d) == True:
    print("True")


    

False


In [5]:
#show me an exmaple of matrix multiplication
import numpy as np
a = np.array([[1,2],[3,4]])
print(a)
b = np.array([[5,6],[7,8]])
print(b)
c = np.dot(a,b)
print(c)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [6]:
#do cross product of a and b
d = np.cross(a,b)
print(d)


[-4 -4]


C:\Users\rashi\AppData\Local\Temp\ipykernel_30304\1763989251.py:2: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  d = np.cross(a,b)


In [ ]:
addies = [1345, 1422, 1353, 1980]

spin = [num for num in addies if num % 2 != 0]

if input("spin"):
    print(spin)